### ISSUE TITLE
Switch to chocolatey_package Resource?

### ISSUE THREAD

**Issue by tknerr** [Zuehlke/cookbook-windev#28]
Newer Chef versions include a `chocolatey_package` resource in Chef core, i.e. no need for the dependency on the chocolatey cookbook anymore:
https://docs.chef.io/resource_chocolatey_package.html

Shall we switch to using the `chocolatey_package` resource directly?

Does cookbook windev have any compatibility guarantees wrt Chef versions?

**Comment by damphyr** [comment]
Yes we should (bar compatibility issues) 

The newly release 0.7.0 sets Chef 12.6 as a prereq.

**Comment by damphyr** [comment]
Done #31
